language: node_js
node_js:
- node
before_script:
- npm run test
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: MCpLUAB0EwlYsGD8SPJ8/msklAy0qX5g/awrfE5NtghctUfcaJWjxNzbt8N6G/3H+NKoCEy0x4G3AwqF3EiFfGoZVPt4/iai76ZhHO/YIrd/MEW5ncjYeQ9Pp2/lIouCdDt/iYaWhX9a+WspqZ4pmikAdUbxrcjeXwgaFWd2HNJqWc1i8Pez7l9c3qPqTDc3ga32TSbgye4AhGmPb3ng22XFnZj5NAuoXqwBb0ppLPOqRCoc8gP3iQea9mgfDre2Me8KA9qBrYnvt9VIys28AX1o3BK5VAxUXChMcUlqqsdSCdXlM7AOZL1PaoxAfP2P4xJwLDdE5SGskBMqE+YR0UUOf0r19jeF5ywgVf7tNN2Ort02VmVpEph3SuwZslawhiVZX7WQhbwM/L0mPd8H/RjVz8KiIB04pFXITBYSlIPhzvmj6NDaAsk9vTbE76ZzX6L0krSdsD51WnbciXGMIqlLl87y9sneOWlwOFS8l8Fq8uiomAR/xC6CpLf5i8BpYmYPo3Ii4HQR/wPlxglWO2MUkDaEVqf2uyZtBFdqUzp1OrhQlh0UAfiyh3LLkLDXxgvuY9rhqu+tOi8I/jI2fCHqhpwGu5854LzuM8IV/FlqN5NgLiaLKSgpuN/sxVYJEJp9CGN6xDT3DMDTYCHDPO/920ZkVJB1VDAVgdDcoh8=
  app: habit-golf
  skip_cleanup: true 
